### ISSUE TITLE
Smaller logo

### ISSUE THREAD

**Issue by igormagalhaesr** [igormagalhaesr/FastAPI-boilerplate#18]
![20231023_232003](https://github.com/igormagalhaesr/FastAPI-boilerplate/assets/43156212/9bd8ae72-04ae-49bf-aeea-ba7af404c6e9)

**Comment by igormagalhaesr** [comment]
![Screenshot 2023-10-25 at 00 42 57](https://github.com/igormagalhaesr/FastAPI-boilerplate/assets/43156212/975d1c98-b1c9-4c8e-b4bd-001c8a5728cb)

**Comment by igorbenav** [comment]
<img width="1423" alt="createfree" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/d9c4f511-4cfa-40c6-b882-5b09df9f62b9">
<img width="1428" alt="createfreetier" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/95d31e19-b798-4f03-98f0-3e9d1844f7b3">
<img width="1422" alt="createpro" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/5a6ca593-ccc0-4965-b2db-09ec5ecad91c">
<img width="1425" alt="createprotier" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/deec6f46-9d47-4f01-9899-ca42da0f0363">
