### ISSUE TITLE
Dbdiagram after making repository public

### ISSUE THREAD

**Issue by igormagalhaesr** [igormagalhaesr/FastAPI-boilerplate#5]
<img width="739" alt="dbdiagram" src="https://github.com/igormagalhaesr/FastAPI-boilerplate/assets/43156212/0531a62d-7740-4c2a-9fd7-7f349cffdc8e">

**Comment by igormagalhaesr** [comment]
<img width="764" alt="Screenshot 2023-10-09 at 00 32 11" src="https://github.com/igormagalhaesr/FastAPI-boilerplate/assets/43156212/31bbdb41-15bf-45f2-8c8e-0b04b71c5b0b">
dark version

**Comment by igorbenav** [comment]
<img width="1161" alt="Screenshot 2023-11-11 at 20 58 35" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/c7a36e26-dcd0-42cf-939d-6434b5579f29">

DB changes

**Comment by igorbenav** [comment]
<img width="318" alt="Screenshot 2023-11-20 at 21 34 47" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/b2f3c0ca-b8ea-4f20-b47e-de1bad2ca283">

<img width="1169" alt="Screenshot 2023-11-20 at 21 35 19" src="https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/bdafc637-0473-4b71-890d-29e79da288cf">
